-- Durable Project Q -> Oracle Platform event outbox.
-- Enrollment and outbox creation are committed atomically; delivery is leased
-- and retried independently so Oracle availability never blocks campaign state.

create table if not exists public.oracle_platform_outbox (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  event_name text not null
    check (event_name in ('campaign.joined','campaign.mission.completed')),
  campaign_id text not null references public.campaigns(id),
  telegram_user_id bigint not null,
  occurred_at timestamptz not null,
  status text not null default 'pending'
    check (status in ('pending','sending','delivered','failed')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  next_attempt_at timestamptz not null default now(),
  lease_id uuid,
  lease_until timestamptz,
  last_error text,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists oracle_platform_outbox_ready_idx
  on public.oracle_platform_outbox (next_attempt_at, id)
  where status in ('pending','failed');

alter table public.oracle_platform_outbox enable row level security;
revoke all on public.oracle_platform_outbox from public, anon, authenticated;
grant select, insert, update on public.oracle_platform_outbox to service_role;
grant usage, select on sequence public.oracle_platform_outbox_id_seq to service_role;

create or replace function public.claim_oracle_platform_outbox(
  p_lease_id uuid,
  p_limit integer default 25
) returns setof public.oracle_platform_outbox
language plpgsql
security invoker
set search_path = public
as $$
begin
  if p_lease_id is null then raise exception 'lease id required'; end if;
  if p_limit is null or p_limit < 1 or p_limit > 100 then raise exception 'invalid limit'; end if;

  return query
  with ready as (
    select id
    from public.oracle_platform_outbox
    where status in ('pending','failed')
      and next_attempt_at <= now()
      and (lease_until is null or lease_until < now())
    order by next_attempt_at, id
    for update skip locked
    limit p_limit
  )
  update public.oracle_platform_outbox o
  set status = 'sending',
      lease_id = p_lease_id,
      lease_until = now() + interval '5 minutes',
      attempt_count = o.attempt_count + 1,
      last_error = null
  from ready
  where o.id = ready.id
  returning o.*;
end;
$$;

create or replace function public.complete_oracle_platform_outbox(
  p_id bigint,
  p_lease_id uuid
) returns boolean
language plpgsql
security invoker
set search_path = public
as $$
begin
  update public.oracle_platform_outbox
  set status = 'delivered',
      delivered_at = now(),
      lease_id = null,
      lease_until = null,
      last_error = null
  where id = p_id
    and status = 'sending'
    and lease_id = p_lease_id;
  return found;
end;
$$;

create or replace function public.fail_oracle_platform_outbox(
  p_id bigint,
  p_lease_id uuid,
  p_error text,
  p_retry_after_seconds integer
) returns boolean
language plpgsql
security invoker
set search_path = public
as $$
begin
  if p_retry_after_seconds is null or p_retry_after_seconds < 30
     or p_retry_after_seconds > 3600 then
    raise exception 'invalid retry delay';
  end if;
  update public.oracle_platform_outbox
  set status = 'failed',
      next_attempt_at = now() + make_interval(secs => p_retry_after_seconds),
      lease_id = null,
      lease_until = null,
      last_error = left(coalesce(p_error, 'delivery_failed'), 120)
  where id = p_id
    and status = 'sending'
    and lease_id = p_lease_id;
  return found;
end;
$$;

revoke all on function public.claim_oracle_platform_outbox(uuid,integer)
  from public, anon, authenticated;
revoke all on function public.complete_oracle_platform_outbox(bigint,uuid)
  from public, anon, authenticated;
revoke all on function public.fail_oracle_platform_outbox(bigint,uuid,text,integer)
  from public, anon, authenticated;
grant execute on function public.claim_oracle_platform_outbox(uuid,integer) to service_role;
grant execute on function public.complete_oracle_platform_outbox(bigint,uuid) to service_role;
grant execute on function public.fail_oracle_platform_outbox(bigint,uuid,text,integer) to service_role;

-- Oracle remains authoritative for Telegram<->X identity. First enrollment into
-- Project Q also creates a canonical campaign.joined outbox fact in the same
-- transaction. Subsequent reconnects preserve the original enrolled_at and do
-- not enqueue another join.
create or replace function public.link_oracle_identity(
  p_campaign_id text,
  p_telegram_user_id bigint,
  p_x_user_id text,
  p_verified_at timestamptz
) returns public.identity_links
language plpgsql
security invoker
set search_path = public
as $$
declare
  result public.identity_links;
  v_existing_enrolled_at timestamptz;
begin
  if p_telegram_user_id is null or p_telegram_user_id <= 0
    or p_x_user_id is null or btrim(p_x_user_id) !~ '^[0-9]{1,30}$'
    or p_verified_at is null
  then
    raise exception 'invalid Oracle identity';
  end if;
  if p_verified_at > now() + interval '5 minutes' then
    raise exception 'Oracle verification timestamp is in the future';
  end if;
  if not exists (select 1 from public.campaigns where id = p_campaign_id) then
    raise exception 'unknown campaign';
  end if;
  if exists (
    select 1 from public.identity_links
    where campaign_id = p_campaign_id
      and telegram_user_id = p_telegram_user_id
      and x_user_id is not null
      and x_user_id <> btrim(p_x_user_id)
  ) then raise exception 'Telegram identity is already linked to another X account'; end if;
  if exists (
    select 1 from public.identity_links
    where campaign_id = p_campaign_id
      and x_user_id = btrim(p_x_user_id)
      and telegram_user_id <> p_telegram_user_id
  ) then raise exception 'X identity is already linked to another Telegram account'; end if;

  select enrolled_at into v_existing_enrolled_at
  from public.identity_links
  where campaign_id = p_campaign_id
    and telegram_user_id = p_telegram_user_id;

  insert into public.identity_links (campaign_id, telegram_user_id, x_user_id, x_verified_at)
  values (p_campaign_id, p_telegram_user_id, btrim(p_x_user_id), p_verified_at)
  on conflict (campaign_id, telegram_user_id) do update
    set x_user_id = excluded.x_user_id,
        x_verified_at = greatest(public.identity_links.x_verified_at, excluded.x_verified_at)
  returning * into result;

  if v_existing_enrolled_at is null then
    insert into public.oracle_platform_outbox(
      event_key, event_name, campaign_id, telegram_user_id, occurred_at
    ) values (
      'campaign.joined:' || p_campaign_id || ':' || p_telegram_user_id::text,
      'campaign.joined',
      p_campaign_id,
      p_telegram_user_id,
      result.enrolled_at
    )
    on conflict (event_key) do nothing;
  end if;

  return result;
end;
$$;

revoke all on function public.link_oracle_identity(text,bigint,text,timestamptz)
  from public, anon, authenticated;
grant execute on function public.link_oracle_identity(text,bigint,text,timestamptz)
  to service_role;
